"""add difficulty to Question

Revision ID: 62e19a5b439b
Revises: 7a1c6de49e3b
Create Date: 2025-06-09 11:14:01.036583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e19a5b439b'
down_revision = '7a1c6de49e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
