"""add quiz_id to Question

Revision ID: 7a1c6de49e3b
Revises: add9341d9a5f
Create Date: 2025-06-09 09:49:40.711356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1c6de49e3b'
down_revision = 'add9341d9a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_question_quiz_id_quiz', 'quiz', ['quiz_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_quiz_id_quiz', type_='foreignkey')
        batch_op.drop_column('quiz_id')

    # ### end Alembic commands ###
