"""Add file_path and uploaded_at to Attachment model

Revision ID: 99b40ce5e63b
Revises: 3dbdb931cf39
Create Date: 2025-06-09 14:59:47.476998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b40ce5e63b'
down_revision = '3dbdb931cf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
