"""Add cascade delete to quiz foreign keys

Revision ID: cf7dbb64d476
Revises: dc2216ed6e22
Create Date: 2025-06-10 09:43:26.518957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7dbb64d476'
down_revision = 'dc2216ed6e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_quiz_id_quiz'), type_='foreignkey')
        batch_op.create_foreign_key('fk_question_quiz_id_quiz', 'quiz', ['quiz_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quiz_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_quiz_answer_submission_id_quiz_submission', 'quiz_submission', ['submission_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quiz_submission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_quiz_submission_quiz_id_quiz', 'quiz', ['quiz_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_submission', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_submission_quiz_id_quiz', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['id'])

    with op.batch_alter_table('quiz_answer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_answer_submission_id_quiz_submission', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz_submission', ['submission_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_quiz_id_quiz', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_question_quiz_id_quiz'), 'quiz', ['quiz_id'], ['id'])

    # ### end Alembic commands ###
