"""Add missing fields to student_profile table

Revision ID: dc2216ed6e22
Revises: 8958798124a9
Create Date: 2025-06-09 23:30:47.935912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2216ed6e22'
down_revision = '8958798124a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('area_of_expertise', sa.String(length=100), nullable=True))
        batch_op.drop_column('years_experience')
        batch_op.drop_column('expertise_area')

    with op.batch_alter_table('quiz_submission', schema=None) as batch_op:
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('answers')
        batch_op.drop_column('submitted_at')

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('learning_style', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('support_needs', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('goal', sa.String(length=200), nullable=True))
        batch_op.drop_column('how_ai_can_help')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('how_ai_can_help', sa.TEXT(), nullable=True))
        batch_op.drop_column('goal')
        batch_op.drop_column('support_needs')
        batch_op.drop_column('learning_style')
        batch_op.drop_column('name')

    with op.batch_alter_table('quiz_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('answers', sa.TEXT(), nullable=True))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('instructor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expertise_area', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('years_experience', sa.INTEGER(), nullable=True))
        batch_op.drop_column('area_of_expertise')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
